# **Numpy**

Numpy is a Python library. It is used for working, with arrays. Numpy is short for "Numerical Python".

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


Numpy is used to work with arrays. The array object in Numpy is called ndarray.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array- like object into the array() method, and it will be converted into an ndarray.

In [ ]:
#Use a tuple to create a Numpy array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


**Numpy Array Indexing**

*Access array element*

Array indexing is the same as accessing an array element. The indexes in Numpy start with 0, meaning that the first element has index 0,and the second has index 1 etc.

In [ ]:
#Get the first element from the following array:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [ ]:
#Get the third and fourth element from the following and add them:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2]+arr[3])

7


*Access 2-d arrays*

To access elements from 2-d arrays ,we can use comma separated integers representing the dimension and the index of the element.Think of 2-d arrays like a table with rows and columns, where the row represents the dimensions and the index represent the column.

In [ ]:
#Access the element on the first row, second column.
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


**Numpy Array Slicing**

*Slicing array*

Slicing in python means taking elements from one given index to another given index.
If we don't pass start its considered 0.If we don't pass end its considered length of array in that dimension.

In [ ]:
#Slice elements from index 1 to index 5 from the following array:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
#Slice elements from index 4 to the end of the array:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [ ]:
#Negative Slicing
#Use the minus operator to refer to an index from the end:
#Slice from index 3 to 1 from the end:

import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [ ]:
#From both elements, slice index 1 to 4, this will return a 2-d array:

import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# Join Two Arrays

In [2]:
import numpy as np
arr1 =np.array([1,2,3])
arr2 =np.array([4,5,6])

arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [5]:
#Join two 2-d arrays along rows
import numpy as np
arr1= np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

arr=np.concatenate((arr1,arr2),axis=1)
print(arr)
arr1=np.concatenate((arr1,arr2),axis=0)
print(arr1)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


The Numpy ndarray object has a function called sort(), that will sort a specified array.

In [6]:
#Sort the array
import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [7]:
#Sort the array alphabetically:
import numpy as np
arr=np.array(["banana","cherry","apple"])
print(np.sort(arr))

['apple' 'banana' 'cherry']


# Sorting a 2-d array

If one use the sort() method on a 2-d array, both will be sorted.

In [8]:
#Sort a 2-d array:
import numpy as np
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
